services:
    nest-app:
        build: .
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            - .:/app
        command: npm run start:prod

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydb
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
