name: CI/CD for NestJS

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker Image
              run: docker build -t nest-app .

            - name: Run Tests (if any)
              run: docker run --rm nest-app npm run test

            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/${{ secrets.EC2_USER }}/my-nest-app

                      # Pull latest code
                      git pull origin master

                      # Create .env file on the EC2 instance
                      echo "${{ secrets.PRODUCTION }}" > .env
                      echo "NODE_ENV=production" >> .env

                      # Restart services
                      docker-compose down
                      docker-compose up -d --build
