name: CI/CD for NestJS ok

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-app:latest .

            - name: Push Docker Image to Docker Hub
              run: docker push ${{ secrets.DOCKER_USERNAME }}/nest-app:latest

            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /home/${{ secrets.EC2_USER }}
                      if [ ! -d "my-nest-app" ]; then
                        git clone https://github.com/mahara0511/deploy-EC2.git my-nest-app
                      fi

                      cd my-nest-app
                      git pull origin master
                      echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

                      # Update .env file
                      echo "${{ secrets.PRODUCTION }}" > .env

                      docker rmi khanhzip14/nest-app:latest
                      # Restart the app
                      docker-compose pull
                      docker-compose down
                      docker-compose up -d
